filter:
  paths: ["src/*"]
  excluded_paths: ["tests/*"]
  dependency_paths: ["vendor/*"]

checks:
  php:
    code_rating: true
    duplication: true

tools:
  external_code_coverage: false

build:
  environment:
    php:
      version: "7.4"
      pecl_extensions:
        - zip
    mysql: false
    node: false
    postgresql: false
    mongodb: false
    elasticsearch: false
    redis: false
    memcached: false
    neo4j: false
    rabbitmq: false
    apt_packages:
      - xvfb
      - libfontconfig
      - wkhtmltopdf
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
    functional-tests:
      environment:
        selenium: true
  dependencies:
    before:
      - composer self-update
      - composer update --no-interaction --prefer-dist --no-progress
      - php artisan dusk:chrome-driver
  tests:
    before:
      -
        command: composer test-coverage
        coverage:
          file: 'build/logs/clover.xml'
          format: 'clover'
